### PR TITLE
Fix silently failing invalid validators in shape

### LINKED ISSUE #220: No warnings for invalid validators inside shape
This could be related to #181 

In a project we noticed that having typos in prop type definitions that are nested inside a `PropTypes.shape` do not generate warnings in version `15.6.2`:

```js
{
  a: PropTypes.shape({
    b: PropTypes.boolean // <- is undefined
  })
}
```

I've boiled it down to these test cases:

Case 1:
```js
const PropTypes = require('prop-types');

PropTypes.checkPropTypes({ a: undefined }, { a: "hello" });
```

Case 2:
```js
const PropTypes = require('prop-types');

PropTypes.checkPropTypes(
  { a: PropTypes.shape({ b: undefined }) },
  { a: { b: "hello" } }
);
```

Case 1 generates a warning, as expected:

```
Warning: Failed undefined type: React class: undefined type `a` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
```

Case 2, however, does not output any error or warning 😞 In other words, it seems like if you use an invalid validator inside a `PropTypes.shape`, validation will always pass and no compile time warning or error is visible, which means there might be potential for some sneaky runtime bugs.

I've tested this in many different versions (as low as `0.2.0` and `0.1.0` and it seems to be consistent across all versions.

Is this somehow the intended behaviour? If so, what is a good way to get compile-time errors/warnings for invalid validators used inside `PropTypes.shape`?

### PR DESCRIPTION
**Pull request by asbjornh**
Fixes #220 
Possibly also #181 

This PR adds type checks for validators in `createShapeTypeChecker` and `createStrictShapeTypeChecker` so that they can fail loudly on invalid validators and everyone can be safe and happy! 😊

As outlined in #220 , providing any falsy value instead of a validator will cause validation to be skipped, meaning invalid props won't be caught. Providing a truthy value that's not a function results in a caught but displayed javascript error `Warning: Failed prop type: checker is not a function` which is better than nothing but not really that helpful.

The most likely cause of issues is typos in validator names, like `PropTypes.boolean` (which I've since discovered that I've written several times). As mentioned in #220 this is mitigated by using `eslint-plugin-react/no-typos`, but I do feel that relying on a third party that's not a dependency is more of a band-aid than a solution.

Another cause would be references to internal or external things that might or might not be functions, which is not caught by the eslint plugin.
```js
const validator = false;
Component.propTypes = {
  foo: PropTypes.shape({ bar: validator })
};
```

### CODE REVIEW

**Comment by ljharb** [comment]
@gaearon do you think this is a bug fix, or a breaking change because it might introduce additional warnings?

**Comment by asbjornh** [comment]
@ljharb In hindsight I think the tests might be a little thin. I'd be happy to add some more invalid cases in both tests unless that's too late now (I don't fully understand what you did with with those force pushes)

**Comment by ljharb** [comment]
@asbjornh definitely not too late! i rebased the PR branch; after a `git fetch` locally you can `git reset --hard origin/fix-invalid-validators-in-shape`, or `git checkout master && git branch -D fix-invalid-validators-in-shape && git checkout fix-invalid-validators-in-shape`, or you can delete and re-clone your local repo.

**Comment by asbjornh** [comment]
Great! Thanks :)

**Comment by asbjornh** [comment]
@ljharb I've added some more test cases (which was good because I discovered an issue). I think this is ready now, unless you guys want any changes :)

File: factoryWithTypeCheckers.js [hunk 1]
```diff
@@ -434,6 +441,9 @@ module.exports = function(isValidElement, throwOnDirectAccess) {
       var allKeys = assign({}, props[propName], shapeTypes);
       for (var key in allKeys) {
         var checker = shapeTypes[key];
+        if (shapeTypes.hasOwnProperty(key) && typeof checker !== 'function') {
```
Comment (ljharb) [inline factoryWithTypeCheckers.js]: Please never rely on `hasOwnProperty` being on an object directly; use `has` instead
```suggestion
        if (has(shapeTypes, key) && typeof checker !== 'function') {
```

File: factoryWithTypeCheckers.js [hunk 2]
```diff
@@ -434,6 +441,9 @@ module.exports = function(isValidElement, throwOnDirectAccess) {
...
+          return invalidValidatorError(componentName, location, propFullName, key, typeof checker);
```
Comment (ljharb) [inline factoryWithTypeCheckers.js]: instead of using `typeof` here, can we use `getPreciseType`?
```suggestion
          return invalidValidatorError(componentName, location, propFullName, key, getPreciseType(checker));
```

File: factoryWithTypeCheckers.js (hunk 1 above)
Comment (asbjornh) [reply factoryWithTypeCheckers.js]: 👍

File: factoryWithTypeCheckers.js (hunk 2 above)
Comment (asbjornh) [reply factoryWithTypeCheckers.js]: Yep!

**Comment by asbjornh** [comment]
Yay!
